// robots.txt, generated by Next at /robots.txt.
//
// The staff side is behind a login, so Google can't read it — but it can still
// list a URL it can't read, and "Betterservice invoices" turning up in search
// results looks bad even when nothing leaks. Name them explicitly instead.
export default function robots() {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: [
        "/dashboard", "/jobs", "/invoices", "/customers", "/machines",
        "/parts", "/suppliers", "/purchase-orders", "/counter-sales",
        "/credit-notes", "/bills", "/expenses", "/accounting", "/reports",
        "/rentals", "/bookings", "/timesheets", "/staff", "/settings",
        "/templates", "/stocktake", "/secondhand", "/due", "/search",
        "/login", "/reset",
      ],
    },
    sitemap: "https://betterservice.co.nz/sitemap.xml",
  };
}
