-- ============================================================================
-- Betterservice Tepuke — accounting core (double-entry ledger)
-- Built the night of 11 July 2026; captured into the repo 14 July 2026 from the
-- live project (vdwssiefdhmepdgkuoxd). Runs after 0001 baseline + 0002 hardening.
-- Adds: chart of accounts, journal (entries + lines), credit notes, payments,
-- the balanced-posting engine + auto-posting triggers, and owner-gated reads.
-- Idempotent: safe to re-run (if-not-exists / or-replace / drop-if-exists).
-- ============================================================================

-- ---------- Ledger tables ----------
create table if not exists public.accounts (
  id          uuid primary key default gen_random_uuid(),
  code        text not null unique,
  name        text not null,
  type        text not null check (type in ('asset','liability','equity','income','expense')),
  is_active   boolean not null default true,
  description text,
  created_at  timestamptz default now()
);

create table if not exists public.journal_entries (
  id                uuid primary key default gen_random_uuid(),
  entry_date        date not null default ((now() at time zone 'Pacific/Auckland'))::date,
  memo              text,
  source_type       text not null default 'manual',
  source_id         uuid,
  reverses_entry_id uuid references public.journal_entries(id),
  created_by        uuid references public.staff(id),
  created_at        timestamptz default now()
);

create table if not exists public.journal_lines (
  id         uuid primary key default gen_random_uuid(),
  entry_id   uuid not null references public.journal_entries(id) on delete cascade,
  account_id uuid not null references public.accounts(id),
  debit      numeric not null default 0 check (debit  >= 0) check (debit  = round(debit, 2)),
  credit     numeric not null default 0 check (credit >= 0) check (credit = round(credit, 2)),
  memo       text,
  constraint not_both_zero check (debit > 0 or credit > 0),
  constraint one_side_only check (debit = 0 or credit = 0)
);

create table if not exists public.credit_notes (
  id                 uuid primary key default gen_random_uuid(),
  credit_note_number bigint generated by default as identity not null,
  invoice_id         uuid references public.invoices(id),
  customer_id        uuid references public.customers(id),
  reason             text,
  subtotal           numeric not null default 0 check (subtotal = round(subtotal, 2)),
  gst                numeric not null default 0 check (gst      = round(gst, 2)),
  total              numeric not null default 0 check (total    = round(total, 2)),
  status             text not null default 'Issued',
  pdf_url            text,
  sent               boolean default false,
  sent_at            timestamptz,
  created_by         uuid references public.staff(id),
  created_at         timestamptz default now()
);

create table if not exists public.payments (
  id         uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references public.invoices(id) on delete cascade,
  amount     numeric not null check (amount > 0) check (amount = round(amount, 2)),
  paid_date  date not null default ((now() at time zone 'Pacific/Auckland'))::date,
  method     text,
  created_by uuid references public.staff(id),
  created_at timestamptz default now()
);

-- ---------- Indexes ----------
create index if not exists journal_entries_date_idx  on public.journal_entries (entry_date);
create index if not exists journal_lines_entry_idx   on public.journal_lines   (entry_id);
create index if not exists journal_lines_account_idx on public.journal_lines   (account_id);
create index if not exists payments_invoice_idx      on public.payments        (invoice_id);

-- ---------- job/invoice numbers moved to auto-increment identity ----------
-- (0001 created these as plain bigint "assigned by the app"; the live DB now
--  auto-assigns them. Guarded so re-runs are a no-op.)
do $$ begin
  if (select attidentity from pg_attribute
        where attrelid = 'public.job_cards'::regclass and attname = 'job_number') = '' then
    alter table public.job_cards alter column job_number add generated by default as identity;
  end if;
end $$;
do $$ begin
  if (select attidentity from pg_attribute
        where attrelid = 'public.invoices'::regclass and attname = 'invoice_number') = '' then
    alter table public.invoices alter column invoice_number add generated by default as identity;
  end if;
end $$;

-- ---------- Chart of accounts (seed) ----------
insert into public.accounts (code, name, type) values
  ('100', 'Business Bank Account',  'asset'),
  ('110', 'Accounts Receivable',    'asset'),
  ('120', 'Parts Inventory',        'asset'),
  ('200', 'GST',                    'liability'),
  ('210', 'Accounts Payable',       'liability'),
  ('300', 'Owner Funds',            'equity'),
  ('310', 'Retained Earnings',      'equity'),
  ('400', 'Sales — Labour',         'income'),
  ('410', 'Sales — Parts',          'income'),
  ('420', 'Sales — Other',          'income'),
  ('500', 'Cost of Parts',          'expense'),
  ('510', 'Wages',                  'expense'),
  ('520', 'Rent',                   'expense'),
  ('530', 'Utilities & Overheads',  'expense'),
  ('540', 'Other Expenses',         'expense')
on conflict (code) do nothing;

-- ---------- Posting engine (every entry must balance) ----------
CREATE OR REPLACE FUNCTION public.post_entry(p_date date, p_memo text, p_source_type text, p_source_id uuid, p_lines jsonb)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_entry  uuid;
  v_debit  numeric;
  v_credit numeric;
  v_bad    text;
begin
  if not is_approved_staff() then raise exception 'Not authorised'; end if;

  select string_agg(distinct (l->>'account_code'), ', ')
    into v_bad
    from jsonb_array_elements(p_lines) l
    where not exists (select 1 from accounts a where a.code = l->>'account_code');
  if v_bad is not null then raise exception 'Unknown account code(s): %', v_bad; end if;

  select coalesce(sum((l->>'debit')::numeric),0), coalesce(sum((l->>'credit')::numeric),0)
    into v_debit, v_credit
    from jsonb_array_elements(p_lines) l;

  if round(v_debit,2) <> round(v_credit,2) then
    raise exception 'Entry does not balance: debits % vs credits %', v_debit, v_credit;
  end if;
  if round(v_debit,2) = 0 then raise exception 'Entry has no value'; end if;

  insert into journal_entries(entry_date, memo, source_type, source_id, created_by)
    values (coalesce(p_date,(now() at time zone 'Pacific/Auckland')::date), p_memo,
            coalesce(p_source_type,'manual'), p_source_id,
            (select id from staff where lower(email)=lower(auth.email()) limit 1))
    returning id into v_entry;

  insert into journal_lines(entry_id, account_id, debit, credit, memo)
  select v_entry,
         (select id from accounts where code = l->>'account_code'),
         round(coalesce((l->>'debit')::numeric,0),2),
         round(coalesce((l->>'credit')::numeric,0),2),
         l->>'memo'
  from jsonb_array_elements(p_lines) l;

  return v_entry;
end $function$;

CREATE OR REPLACE FUNCTION public.reverse_entry(p_entry uuid, p_date date, p_memo text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_new uuid;
begin
  if not is_approved_staff() then raise exception 'Not authorised'; end if;
  insert into journal_entries(entry_date, memo, source_type, source_id, reverses_entry_id, created_by)
    values (coalesce(p_date,(now() at time zone 'Pacific/Auckland')::date),
            coalesce(p_memo,'Reversal'), 'reversal',
            (select source_id from journal_entries where id = p_entry),
            p_entry, (select id from staff where lower(email)=lower(auth.email()) limit 1))
    returning id into v_new;
  insert into journal_lines(entry_id, account_id, debit, credit, memo)
    select v_new, account_id, credit, debit, memo   -- swap debit/credit to reverse
    from journal_lines where entry_id = p_entry;
  return v_new;
end $function$;

-- ---------- Auto-posting triggers' functions ----------
CREATE OR REPLACE FUNCTION public.ledger_on_invoice_insert()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_lab numeric; v_par numeric; v_base numeric;
  v_clab numeric := 0; v_cpar numeric := 0; v_coth numeric; v_lines jsonb; v_no text;
begin
  if exists (select 1 from journal_entries where source_type='invoice' and source_id = NEW.id) then
    return NEW;
  end if;
  v_no := 'Invoice #' || lpad(NEW.invoice_number::text, 5, '0');

  select coalesce(sum(case when kind='labour' then amount else 0 end),0),
         coalesce(sum(case when kind='part'   then amount else 0 end),0)
    into v_lab, v_par
    from job_line_items where job_card_id = NEW.job_card_id;
  v_base := v_lab + v_par;
  v_coth := coalesce(NEW.subtotal,0);
  if v_base > 0 then
    v_clab := round(coalesce(NEW.subtotal,0) * v_lab / v_base, 2);
    v_cpar := round(coalesce(NEW.subtotal,0) * v_par / v_base, 2);
    v_coth := round(coalesce(NEW.subtotal,0) - v_clab - v_cpar, 2);
  end if;

  v_lines := jsonb_build_array(jsonb_build_object('account_code','110','debit', NEW.total, 'memo', v_no));
  if v_clab > 0 then v_lines := v_lines || jsonb_build_object('account_code','400','credit', v_clab); end if;
  if v_cpar > 0 then v_lines := v_lines || jsonb_build_object('account_code','410','credit', v_cpar); end if;
  if v_coth <> 0 then v_lines := v_lines || jsonb_build_object('account_code','420','credit', v_coth); end if;
  if coalesce(NEW.gst,0) > 0 then v_lines := v_lines || jsonb_build_object('account_code','200','credit', NEW.gst); end if;

  perform post_entry(coalesce(NEW.issued_date, current_date), v_no, 'invoice', NEW.id, v_lines);
  return NEW;
end $function$;

CREATE OR REPLACE FUNCTION public.ledger_on_payment_insert()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_num bigint; v_no text;
begin
  if exists (select 1 from journal_entries where source_type='payment' and source_id = NEW.id) then return NEW; end if;
  select invoice_number into v_num from invoices where id = NEW.invoice_id;
  v_no := 'Payment — Invoice #' || lpad(coalesce(v_num,0)::text, 5, '0');
  perform post_entry(coalesce(NEW.paid_date, current_date), v_no, 'payment', NEW.id,
    jsonb_build_array(
      jsonb_build_object('account_code','100','debit',  NEW.amount),
      jsonb_build_object('account_code','110','credit', NEW.amount)
    ));
  return NEW;
end $function$;

CREATE OR REPLACE FUNCTION public.ledger_on_credit_note_insert()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_no text; v_lines jsonb;
  v_inv_sub numeric; v_lab numeric; v_par numeric;
  v_clab numeric := 0; v_cpar numeric := 0; v_coth numeric;
begin
  if exists (select 1 from journal_entries where source_type='credit_note' and source_id = NEW.id) then
    return NEW;
  end if;
  v_no  := 'Credit note #' || lpad(NEW.credit_note_number::text, 5, '0');
  v_coth := coalesce(NEW.subtotal,0);

  if NEW.invoice_id is not null then
    select i.subtotal,
           coalesce(sum(case when li.kind='labour' then li.amount else 0 end),0),
           coalesce(sum(case when li.kind='part'   then li.amount else 0 end),0)
      into v_inv_sub, v_lab, v_par
      from invoices i left join job_line_items li on li.job_card_id = i.job_card_id
      where i.id = NEW.invoice_id group by i.subtotal;
    if coalesce(v_inv_sub,0) > 0 then
      v_clab := round(coalesce(NEW.subtotal,0) * (v_lab / v_inv_sub), 2);
      v_cpar := round(coalesce(NEW.subtotal,0) * (v_par / v_inv_sub), 2);
      v_coth := round(coalesce(NEW.subtotal,0) - v_clab - v_cpar, 2);
    end if;
  end if;

  v_lines := jsonb_build_array(
    jsonb_build_object('account_code','110','credit', NEW.total, 'memo', v_no)
  );
  if v_clab > 0 then v_lines := v_lines || jsonb_build_object('account_code','400','debit', v_clab); end if;
  if v_cpar > 0 then v_lines := v_lines || jsonb_build_object('account_code','410','debit', v_cpar); end if;
  if v_coth <> 0 then v_lines := v_lines || jsonb_build_object('account_code','420','debit', v_coth); end if;
  if coalesce(NEW.gst,0) > 0 then v_lines := v_lines || jsonb_build_object('account_code','200','debit', NEW.gst); end if;

  perform post_entry(coalesce(NEW.created_at::date, current_date), v_no, 'credit_note', NEW.id, v_lines);
  return NEW;
end $function$;

CREATE OR REPLACE FUNCTION public.sync_invoice_status()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_inv uuid; v_total numeric; v_paid numeric; v_status text; v_last date;
begin
  v_inv := coalesce(NEW.invoice_id, OLD.invoice_id);
  select total into v_total from invoices where id = v_inv;
  select coalesce(sum(amount),0), max(paid_date) into v_paid, v_last from payments where invoice_id = v_inv;
  v_status := case when v_paid <= 0 then 'Unpaid'
                   when v_paid >= coalesce(v_total,0) then 'Paid'
                   else 'Part-paid' end;
  update invoices set status = v_status,
                      paid_date = case when v_status='Paid' then v_last else null end
    where id = v_inv;
  return null;
end $function$;

-- ---------- Owner-gated reporting reads ----------
CREATE OR REPLACE FUNCTION public.accounting_overview()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare result jsonb;
begin
  if not is_owner() then raise exception 'Owners only'; end if;
  select jsonb_build_object(
    'accounts', (
      select coalesce(jsonb_agg(jsonb_build_object('code',a.code,'name',a.name,'type',a.type,'balance',coalesce(b.bal,0)) order by a.code), '[]'::jsonb)
      from accounts a
      left join (select account_id, sum(debit-credit) bal from journal_lines group by account_id) b on b.account_id = a.id
    ),
    'monthly_income', (
      select coalesce(jsonb_agg(jsonb_build_object('month', m.month, 'income', m.income) order by m.month desc), '[]'::jsonb)
      from (select to_char(je.entry_date,'YYYY-MM') as month, sum(jl.credit - jl.debit) as income
            from journal_lines jl join journal_entries je on je.id = jl.entry_id join accounts a on a.id = jl.account_id
            where a.type = 'income' group by 1 order by 1 desc limit 12) m
    ),
    'recent', (
      select coalesce(jsonb_agg(jsonb_build_object('date', r.entry_date, 'memo', r.memo, 'type', r.source_type, 'amount', r.amount) order by r.entry_date desc, r.created_at desc), '[]'::jsonb)
      from (select je.entry_date, je.memo, je.source_type, je.created_at,
                   (select sum(debit) from journal_lines where entry_id = je.id) as amount
            from journal_entries je order by je.entry_date desc, je.created_at desc limit 20) r
    )
  ) into result;
  return coalesce(result, '{}'::jsonb);
end $function$;

CREATE OR REPLACE FUNCTION public.outstanding_statements()
 RETURNS jsonb
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select coalesce(jsonb_agg(c order by (c->>'customer_name')), '[]'::jsonb) from (
    select jsonb_build_object(
      'customer_name', cu.name,
      'email', cu.email,
      'total_owing', sum(i.total - coalesce(p.paid,0)),
      'invoices', jsonb_agg(jsonb_build_object(
         'number', i.invoice_number,
         'date',   i.issued_date,
         'total',  i.total,
         'paid',   coalesce(p.paid,0),
         'balance', i.total - coalesce(p.paid,0)
      ) order by i.invoice_number)
    ) as c
    from invoices i
    join job_cards j  on j.id = i.job_card_id
    join customers cu on cu.id = j.customer_id
    left join (select invoice_id, sum(amount) paid from payments group by invoice_id) p on p.invoice_id = i.id
    where i.status in ('Unpaid','Part-paid')
      and (i.total - coalesce(p.paid,0)) > 0.005
      and cu.email is not null
    group by cu.id, cu.name, cu.email
  ) sub;
$function$;

grant execute on function public.accounting_overview()   to authenticated;
grant execute on function public.outstanding_statements() to authenticated;

-- ---------- Auto-posting triggers ----------
drop trigger if exists trg_ledger_invoice_insert on public.invoices;
create trigger trg_ledger_invoice_insert after insert on public.invoices
  for each row execute function ledger_on_invoice_insert();

drop trigger if exists trg_ledger_payment_insert on public.payments;
create trigger trg_ledger_payment_insert after insert on public.payments
  for each row execute function ledger_on_payment_insert();

drop trigger if exists trg_sync_invoice_status on public.payments;
create trigger trg_sync_invoice_status after insert or delete on public.payments
  for each row execute function sync_invoice_status();

drop trigger if exists trg_ledger_credit_note_insert on public.credit_notes;
create trigger trg_ledger_credit_note_insert after insert on public.credit_notes
  for each row execute function ledger_on_credit_note_insert();

-- ---------- Row-level security ----------
alter table public.accounts        enable row level security;
alter table public.journal_entries enable row level security;
alter table public.journal_lines   enable row level security;
alter table public.credit_notes    enable row level security;
alter table public.payments        enable row level security;

-- Accounts + journal: owner-only reads (all writes go through the SECURITY DEFINER functions above).
drop policy if exists accounts_read  on public.accounts;
create policy accounts_read  on public.accounts for select to authenticated using (is_owner());
drop policy if exists accounts_write on public.accounts;
create policy accounts_write on public.accounts for all to authenticated using (is_owner()) with check (is_owner());

drop policy if exists je_read on public.journal_entries;
create policy je_read on public.journal_entries for select to authenticated using (is_owner());
drop policy if exists jl_read on public.journal_lines;
create policy jl_read on public.journal_lines for select to authenticated using (is_owner());

-- Credit notes: staff read + insert; owner update/delete.
drop policy if exists cn_select on public.credit_notes;
create policy cn_select on public.credit_notes for select to authenticated using (is_approved_staff());
drop policy if exists cn_insert on public.credit_notes;
create policy cn_insert on public.credit_notes for insert to authenticated with check (is_approved_staff());
drop policy if exists cn_update on public.credit_notes;
create policy cn_update on public.credit_notes for update to authenticated using (is_owner()) with check (is_owner());
drop policy if exists cn_delete on public.credit_notes;
create policy cn_delete on public.credit_notes for delete to authenticated using (is_owner());

-- Payments: staff read + insert; owner delete.
drop policy if exists pay_select on public.payments;
create policy pay_select on public.payments for select to authenticated using (is_approved_staff());
drop policy if exists pay_insert on public.payments;
create policy pay_insert on public.payments for insert to authenticated with check (is_approved_staff());
drop policy if exists pay_delete on public.payments;
create policy pay_delete on public.payments for delete to authenticated using (is_owner());
