-- ============================================================================
-- Betterservice Tepuke — expenses (Phase 2a)
-- Built 13–14 July 2026; captured into the repo 14 July 2026 from the live
-- project. Runs after 0003 (needs the accounts + journal + post_entry engine).
-- Records a cost; a trigger auto-posts the balanced journal (DR expense +
-- DR 200 GST input / CR 100 Bank or 210 Payables). Idempotent.
-- ============================================================================

create table if not exists public.expenses (
  id              uuid primary key default gen_random_uuid(),
  expense_number  bigint generated by default as identity not null,
  expense_date    date not null default ((now() at time zone 'Pacific/Auckland'))::date,
  supplier        text,
  description     text,
  account_id      uuid not null references public.accounts(id),
  amount_ex_gst   numeric(12,2) not null default 0 check (amount_ex_gst = round(amount_ex_gst, 2) and amount_ex_gst >= 0),
  gst             numeric(12,2) not null default 0 check (gst = round(gst, 2) and gst >= 0),
  total           numeric(12,2) generated always as (round(amount_ex_gst + gst, 2)) stored,
  gst_claimable   boolean not null default true,
  paid_on_account boolean not null default false,
  paid_date       date,
  method          text,
  receipt_url     text,
  status          text not null default 'Unpaid' check (status in ('Unpaid','Paid')),
  created_by      uuid references public.staff(id),
  created_at      timestamptz default now(),
  constraint expenses_gst_only_if_claimable check (gst_claimable or gst = 0)
);

create index if not exists expenses_account_id_idx   on public.expenses (account_id);
create index if not exists expenses_expense_date_idx on public.expenses (expense_date);

-- Auto-post the balanced journal on each expense.
CREATE OR REPLACE FUNCTION public.ledger_on_expense_insert()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_code        text;
  v_no          text;
  v_lines       jsonb;
  v_credit_code text;
begin
  if exists (select 1 from journal_entries where source_type='expense' and source_id = NEW.id) then
    return NEW;
  end if;

  select code into v_code from accounts where id = NEW.account_id;
  if v_code is null then raise exception 'Expense has no valid account'; end if;

  v_no := 'Expense EXP-' || lpad(NEW.expense_number::text, 5, '0') || coalesce(' — ' || NEW.supplier, '');
  v_credit_code := case when NEW.paid_on_account then '210' else '100' end;

  v_lines := jsonb_build_array(
    jsonb_build_object('account_code', v_code, 'debit', NEW.amount_ex_gst, 'memo', coalesce(NEW.description, v_no))
  );
  if coalesce(NEW.gst,0) > 0 then
    v_lines := v_lines || jsonb_build_object('account_code','200','debit', NEW.gst, 'memo','Input GST');
  end if;
  v_lines := v_lines || jsonb_build_object('account_code', v_credit_code, 'credit', NEW.total);

  perform post_entry(coalesce(NEW.expense_date, (now() at time zone 'Pacific/Auckland')::date),
                     v_no, 'expense', NEW.id, v_lines);
  return NEW;
end
$function$;

drop trigger if exists trg_ledger_expense_insert on public.expenses;
create trigger trg_ledger_expense_insert after insert on public.expenses
  for each row execute function ledger_on_expense_insert();

-- Expenses: approved staff can record and view (money-out data entry).
alter table public.expenses enable row level security;
drop policy if exists expenses_staff_all on public.expenses;
create policy expenses_staff_all on public.expenses for all to authenticated using (is_approved_staff()) with check (is_approved_staff());
