-- ============================================================================
-- Betterservice Tepuke — purchase orders (Phase 3b)
-- Built 14 July 2026. Runs after 0003 (accounts/expenses engine) + 0007 (parts/suppliers/stock_adjustments).
-- Order parts from a supplier, then "receive" with the ACTUAL quantities/costs.
-- Receiving bumps stock (logged as a 'Received' adjustment) and posts the goods
-- as an on-account expense (Cost of Parts + input GST / Accounts Payable), which
-- auto-flows to the ledger via the existing expense trigger. Posting is on actuals,
-- so order-vs-received discrepancies are handled; the expense stays editable.
-- ============================================================================

create table if not exists public.purchase_orders (
  id            uuid primary key default gen_random_uuid(),
  po_number     bigint generated by default as identity not null,
  supplier_id   uuid references public.suppliers(id),
  status        text not null default 'Draft' check (status in ('Draft','Ordered','Received','Cancelled')),
  order_date    date not null default ((now() at time zone 'Pacific/Auckland'))::date,
  expected_date date,
  received_date date,
  expense_id    uuid references public.expenses(id) on delete set null,
  notes         text,
  created_by    uuid references public.staff(id),
  created_at    timestamptz default now()
);

create table if not exists public.purchase_order_items (
  id           uuid primary key default gen_random_uuid(),
  po_id        uuid not null references public.purchase_orders(id) on delete cascade,
  part_id      uuid references public.parts(id) on delete set null,
  description  text not null,
  qty_ordered  integer not null default 1 check (qty_ordered > 0),
  unit_cost    numeric(12,2) not null default 0 check (unit_cost >= 0),
  qty_received integer not null default 0,
  created_at   timestamptz default now()
);
create index if not exists po_items_po_idx on public.purchase_order_items (po_id);

create or replace function public.receive_purchase_order(p_po_id uuid, p_lines jsonb, p_gst numeric)
 returns uuid
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_status text; v_sup text; v_acct uuid; v_no text; v_staff uuid;
  v_goods numeric := 0; v_gst numeric; v_exp uuid;
  l jsonb; v_qty integer; v_cost numeric; v_part uuid; v_cur integer;
begin
  if not is_approved_staff() then raise exception 'Not authorised'; end if;

  select status into v_status from purchase_orders where id = p_po_id;
  if v_status is null then raise exception 'Purchase order not found'; end if;
  if v_status = 'Received' then raise exception 'This order has already been received'; end if;

  select s.name, lpad(po.po_number::text, 5, '0')
    into v_sup, v_no
    from purchase_orders po left join suppliers s on s.id = po.supplier_id
    where po.id = p_po_id;
  select id into v_acct from accounts where code = '500';
  if v_acct is null then raise exception 'Cost of Parts account (500) missing'; end if;
  select id into v_staff from staff where lower(email) = lower(auth.email()) limit 1;

  for l in select * from jsonb_array_elements(p_lines)
  loop
    v_qty  := coalesce((l->>'qty_received')::integer, 0);
    v_cost := coalesce((l->>'unit_cost')::numeric, 0);
    update purchase_order_items
       set qty_received = v_qty, unit_cost = v_cost
     where id = (l->>'item_id')::uuid and po_id = p_po_id
     returning part_id into v_part;

    if v_qty > 0 and v_part is not null then
      select qty_on_hand into v_cur from parts where id = v_part for update;
      insert into stock_adjustments(part_id, delta, new_qty, reason, note, created_by)
        values (v_part, v_qty, coalesce(v_cur,0) + v_qty, 'Received', 'PO #' || v_no, v_staff);
      update parts set qty_on_hand = coalesce(v_cur,0) + v_qty where id = v_part;
    end if;

    v_goods := v_goods + (v_qty * v_cost);
  end loop;

  v_goods := round(v_goods, 2);
  v_gst := round(coalesce(p_gst, v_goods * 0.15), 2);

  if v_goods > 0 then
    insert into expenses(expense_date, supplier, description, account_id, amount_ex_gst, gst, gst_claimable, paid_on_account, method, status)
      values ((now() at time zone 'Pacific/Auckland')::date, v_sup, 'Purchase order #' || v_no,
              v_acct, v_goods, v_gst, true, true, 'account', 'Unpaid')
      returning id into v_exp;
  end if;

  update purchase_orders
     set status = 'Received', received_date = (now() at time zone 'Pacific/Auckland')::date, expense_id = v_exp
   where id = p_po_id;

  return v_exp;
end
$function$;
grant execute on function public.receive_purchase_order(uuid, jsonb, numeric) to authenticated;

alter table public.purchase_orders      enable row level security;
alter table public.purchase_order_items enable row level security;

drop policy if exists po_staff_all on public.purchase_orders;
create policy po_staff_all on public.purchase_orders for all to authenticated using (is_approved_staff()) with check (is_approved_staff());
drop policy if exists po_items_staff_all on public.purchase_order_items;
create policy po_items_staff_all on public.purchase_order_items for all to authenticated using (is_approved_staff()) with check (is_approved_staff());
