-- ============================================================================
-- Betterservice Te Puke — counter sales / quick POS (Phase 3e)
-- Built 14 July 2026. Runs after 0003 (accounts/ledger) + 0007 (parts).
-- Over-the-counter retail (parts & accessories) with no job card: records the
-- sale + items, draws down stock, and posts to the ledger
-- (DR 100 Bank total / CR 410 Sales—Parts subtotal / CR 200 GST). Includes a
-- generic "Cash Sale" customer used as the default for anonymous walk-ins.
-- ============================================================================

insert into public.customers (name)
select 'Cash Sale'
where not exists (select 1 from public.customers where name = 'Cash Sale');

create table if not exists public.counter_sales (
  id             uuid primary key default gen_random_uuid(),
  sale_number    bigint generated by default as identity not null,
  customer_id    uuid references public.customers(id) on delete set null,
  subtotal       numeric(12,2) not null default 0 check (subtotal = round(subtotal, 2)),
  gst            numeric(12,2) not null default 0 check (gst = round(gst, 2)),
  total          numeric(12,2) not null default 0 check (total = round(total, 2)),
  payment_method text,
  created_by     uuid references public.staff(id),
  created_at     timestamptz default now()
);

create table if not exists public.counter_sale_items (
  id          uuid primary key default gen_random_uuid(),
  sale_id     uuid not null references public.counter_sales(id) on delete cascade,
  part_id     uuid references public.parts(id) on delete set null,
  description text not null,
  quantity    integer not null default 1 check (quantity > 0),
  unit_price  numeric(12,2) not null default 0 check (unit_price >= 0),
  amount      numeric(12,2) generated always as (round(quantity * unit_price, 2)) stored
);
create index if not exists counter_sale_items_sale_idx on public.counter_sale_items (sale_id);

create or replace function public.create_counter_sale(p_customer_id uuid, p_items jsonb, p_method text)
 returns jsonb
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_cust uuid; v_sale uuid; v_no bigint; v_staff uuid;
  v_sub numeric := 0; v_gst numeric; v_total numeric; v_lines jsonb;
  l jsonb; v_part uuid; v_qty integer; v_price numeric; v_desc text;
begin
  if not is_approved_staff() then raise exception 'Not authorised'; end if;
  if p_items is null or jsonb_array_length(p_items) = 0 then raise exception 'No items in the sale'; end if;

  for l in select * from jsonb_array_elements(p_items) loop
    v_qty := coalesce((l->>'quantity')::integer, 0);
    v_price := coalesce((l->>'unit_price')::numeric, 0);
    v_sub := v_sub + round(v_qty * v_price, 2);
  end loop;
  v_sub := round(v_sub, 2);
  if v_sub <= 0 then raise exception 'Sale total must be greater than zero'; end if;
  v_gst := round(v_sub * 0.15, 2);
  v_total := round(v_sub + v_gst, 2);

  v_cust := coalesce(p_customer_id, (select id from customers where name = 'Cash Sale' limit 1));
  select id into v_staff from staff where lower(email) = lower(auth.email()) limit 1;

  insert into counter_sales (customer_id, subtotal, gst, total, payment_method, created_by)
    values (v_cust, v_sub, v_gst, v_total, nullif(p_method, ''), v_staff)
    returning id, sale_number into v_sale, v_no;

  for l in select * from jsonb_array_elements(p_items) loop
    v_part := nullif(l->>'part_id', '')::uuid;
    v_qty := coalesce((l->>'quantity')::integer, 0);
    v_price := coalesce((l->>'unit_price')::numeric, 0);
    v_desc := coalesce(nullif(l->>'description', ''), 'Item');
    insert into counter_sale_items (sale_id, part_id, description, quantity, unit_price)
      values (v_sale, v_part, v_desc, v_qty, v_price);
    if v_part is not null then
      update parts set qty_on_hand = qty_on_hand - v_qty where id = v_part;
    end if;
  end loop;

  v_lines := jsonb_build_array(
    jsonb_build_object('account_code', '100', 'debit', v_total),
    jsonb_build_object('account_code', '410', 'credit', v_sub)
  );
  if v_gst > 0 then
    v_lines := v_lines || jsonb_build_object('account_code', '200', 'credit', v_gst);
  end if;

  perform post_entry((now() at time zone 'Pacific/Auckland')::date,
                     'Counter sale #' || lpad(v_no::text, 5, '0'), 'counter_sale', v_sale, v_lines);

  return jsonb_build_object('sale_id', v_sale, 'sale_number', v_no, 'subtotal', v_sub, 'gst', v_gst, 'total', v_total);
end
$function$;
grant execute on function public.create_counter_sale(uuid, jsonb, text) to authenticated;

alter table public.counter_sales      enable row level security;
alter table public.counter_sale_items enable row level security;
drop policy if exists cs_staff_all on public.counter_sales;
create policy cs_staff_all on public.counter_sales for all to authenticated using (is_approved_staff()) with check (is_approved_staff());
drop policy if exists csi_staff_all on public.counter_sale_items;
create policy csi_staff_all on public.counter_sale_items for all to authenticated using (is_approved_staff()) with check (is_approved_staff());
